### ISSUE TITLE
The invoice merging module works in Odoo

### ISSUE THREAD

**Issue by nono6677** [julius-network-solutions/julius-openobject-addons#12]
Hi,

I have tested the invoice merging in Odoo and it works.

Otherwise, it's normal that invoice lines are not merged when they are the same ?
And, It's possible to add an option for accept the invoice lines merging or not? (when they are the same)

Best regards,

**Comment by flotho** [comment]
Hy,

Actually it's not totttaly true.
Working on latest git pull of odoo and latest git pull of your repo I got this error :
```
File "/home/nono/DEV/lib_Odoo/Julius_8.0/julius-openobject-addons/account_invoice_merge_no_unlink_5/object/invoice.py", line 39, in __init__
    if self._columns.get('state'):
```

**Comment by nono6677** [comment]
+1 On latest git pull doesn't works 
I tried with the git version 9ffa3a5 of Odoo server and it's ok

**Comment by mathieuvatel** [comment]
Hello,

I've fixed the installation issue, but as the module hasn't been tested yet, it will stay as not installable yet.
It was developped for the 6.1 version in the first place, then migrated to 7.0 version but not migrated to the v 8.0.

Best regards.

**Comment by flotho** [comment]
Hy @mathieuvatel 
I've tested your update and the manyone is not correctly called. It should be Many2one with uppercase

**Comment by mathieuvatel** [comment]
Hy @flotho 

You're right ! Thank you for this comment !
I've fixed this now.

Best regards.
