### ISSUE TITLE
9.0 branch

### ISSUE THREAD

**Issue by flotho** [julius-network-solutions/julius-openobject-addons#20]
Hi,

I would like to port some of your modules on v9. Any chance you create a new branch?
regards

**Comment by mathieuvatel** [comment]
Hi,

I've just created the 9.0 branch.
Best regards.

**Comment by flotho** [comment]
Great,

What is your strategy for migration? put everything in unported? Use the installable flag?

**Comment by mathieuvatel** [comment]
I think the best strategy is to put it in a folder unported as I haven't much time to put all of the module to not installable

**Comment by mathieuvatel** [comment]
I've put all the modules in the "__unported__" folder

**Comment by flotho** [comment]
Thanks
